### ISSUE TITLE
Microphone permissions

### ISSUE THREAD

**Issue by unic0x** [beeping-io/beeping-examples#1]
The current demo doesn't call android permission a check is done in the SDK but this doesn't trigger the correct permission calls.

To replicate the issue first download the Android Demo and Install it will crash upon first install.

**Comment by alfredrc** [comment]
ERROR:

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.beeping.beeping_hello, PID: 20842
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.beeping.beeping_hello/io.beeping.beeping_hello.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference.

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
        at android.content.ContextWrapper.getPackageManager(ContextWrapper.java:96)
        at android.app.Activity.requestPermissions(Activity.java:4583)
        at androidx.core.app.ActivityCompat.requestPermissions(ActivityCompat.java:502)
        at com.beeping.AndroidBeepingCore.BeepingCore.checkMicrophone(BeepingCore.java:220)
        at com.beeping.AndroidBeepingCore.BeepingCore.startBeepingListen(BeepingCore.java:180)
        **at io.beeping.beeping_hello.MainActivity.onCreate(MainActivity.java:22)**
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)

**Comment by OxySound** [comment]
I found that because the SDK was requesting a service at runtime if I commented out the microphone check in the SDK and moved the check to the application space it resolved the issue.

**Comment by alfredrc** [comment]
Fix!

I have change this line of the SDK of Android at BeepingCore Class:

ActivityCompat.requestPermissions(**(Activity)this.bContext**, new String[]{"android.permission.RECORD_AUDIO"}, 1);
